Squashed '.config/nvim/bundle/neomake/' changes from babc3b1..1abc712
1abc712 README updates (#651)
fd7d1af Fix "make testnvim" on OS X (#658)
2c07cd8 Migrate airline extension to vim-airline repo (#655)
3991eb7 Add abort arguments
26d8838 Make hlint output more readable
d3a69ce Add golint as Warning instead of Error (#654)
cc6475e Fix luac errorformat
1623073 Cache Haskell maker availability checks (#644)
0af0483 Rust: add clippy maker (#616)
ecf4183 Fix neomake#utils#CompressWhitespace tests (#647)
a89702e Use full msg with Vader's Log in neomake#utils#LogMessage
a301ba7 Fix Travis: only build master and split Docker into separate jobs (#643)
7bd3254 Independent fixes from the vim-async branch/PR (#642)
2b67775 Add neomake#utils#redir to use new execute(), which is more reliable (#641)
de1cb8e Fix neomake#utils#GetSetting for lists (#640)
33f7c4c Add Krihelimeter badge
b673e49 Add flake8 error code to displayed error message (#610)
2600cfd Fix vint errors with Python maker
1c2001a Add "Neomake with windo" test, for 07f3807 (#635)
a626c9d test: add "neomake#GetMaker uses defaults from b:/g:" (#633)
7616520 Fix tests for NeomakeInfo
bb04ae6 Better issue template through `:verb NeomakeInfo`
b49189a Factor out getting buffer/global setting into neomake#utils#GetSetting (#631)
07f3807 GetMakerKey: expect maker.name and use maker.bufnr (#629)
1ac37c1 Add neomake#utils#CompressWhitespace (#628)
1f334e6 puppet: specify --color=false in parser validate output (#626)
e0a7bd8 Travis: vint-diff: ignore errors about missing abort attribute
52d4300 Fix tests: https://github.com/neomake/neomake/pull/575#issuecomment-249033234 (#625)
ade408e Ensure that the &efm is valid when emptying the list (#623)
52c5de3 Dockerfile.tests: use neomake/vim-testbed:latest
39a7ac1 Update Haskell section in README. (#621)
1eb51c0 NeomakeInfo: only display settings starting with neomake_ (#622)
85e8ae2 Improve GitHub issue template slightly

git-subtree-dir: .config/nvim/bundle/neomake
git-subtree-split: 1abc71276cc6b287f634c174ac00379d0bfa9098

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,6 +6,10 @@ language: python
 python:
   - "3.5"
 
+branches:
+  only:
+    - master
+
 cache:
   pip: true
 before_cache:
@@ -14,7 +18,10 @@ before_cache:
 
 env:
   matrix:
-    - ENV=docker_test_all
+    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim73
+    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim74-trusty
+    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim74-xenial
+    - ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim-master
     - ENV=vint-diff
     - ENV=vint-errors
     - ENV=vimlint-errors
@@ -30,19 +37,22 @@ matrix:
     - env: ENV=vimlint
     - env: ENV=vint
     # There are currently 3 remaining issues with the java maker.
-    # Ref: https://github.com/neomake/neomake/pull/437
+    # Ref: https://github.com/neomake/neomake/issues/569
     - env: ENV=vimlint-errors
+  fast_finish: true
 
 install:
   - |
     if [ "$ENV" = "vint-diff" ]; then
       # Run full vint against changed files.
+      echo "Looking for changed files in $TRAVIS_COMMIT_RANGE."
       export CHANGED_VIM_FILES="$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep '\.vim$')"
       if [ -z "$CHANGED_VIM_FILES" ]; then
         echo "No changed .vim files: skipping build."
         ENV=SKIP_BUILD
       fi
     elif [ "$ENV" = "vimhelplint" ]; then
+      echo "Looking for changed files in $TRAVIS_COMMIT_RANGE."
       if git diff --exit-code --quiet "$TRAVIS_COMMIT_RANGE" doc/neomake.txt; then
         echo "No changed doc files: skipping build."
         ENV=SKIP_BUILD
@@ -66,9 +76,15 @@ script:
       echo "Skipping build script: see above for any reason."
     elif [ "$ENV" = "vint-diff" ]; then
       if [ -n "$CHANGED_VIM_FILES" ]; then
-        vint $CHANGED_VIM_FILES
+        vint $CHANGED_VIM_FILES | grep -v '^autoload/neomake/makers/.*Use the abort attribute for functions in autoload'
+        if [ "$?" != 1 ]; then
+          echo "vint-diff found errors."
+          exit 1
+        fi
       fi
     else
-      vim --version
-      make $ENV
+      if [[ "$ENV" = "testvim" ]]; then
+        vim --version
+      fi
+      make $ENV $MAKE_ARGS
     fi
